# Generated by Django 3.2.4 on 2021-07-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sortnpage", "0005_daterangeandduration"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_notes",
            field=models.TextField(default=""),
        ),
    ]
