# Generated by Django 3.2.4 on 2021-06-24 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bulkupdate", "0002_auto_20210520_0738"),
    ]

    operations = [
        migrations.CreateModel(
            name="Todo_Child",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_task", models.CharField(max_length=100)),
                ("active_flag", models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name="todo",
            name="todo_child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_child_todo",
                to="bulkupdate.todo_child",
            ),
        ),
    ]
