# Generated by Django 3.2.4 on 2021-06-24 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("bulkupdate", "0003_auto_20210624_1239"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="todo_child",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="todo_child_todo",
                to="bulkupdate.todo_child",
            ),
            preserve_default=False,
        ),
    ]
